### ISSUE TITLE
7.4.33-4 from 7.4.33-2 - breaking issue with crypt function

### ISSUE THREAD

**Issue by jasondowzell** [remicollet/php-src-security#7]
Updated to PHP 7.4.33-4 this morning and crypt function "breaks"

Current code is:

```
$hashed_pass = crypt($password, $Blowfish_Pre . $unique_salt . $Blowfish_End);
if ($hashed_pass==$stored_password) {

```
This return true in PHP 7.4.33-2 but in PHP 7.4.33-4 it returns false

**Comment by YumeMichi** [comment]
Your `$unique_salt` contains `$`?

**Comment by remicollet** [comment]
Inactive, so closing
